version: "3.8"

services:
  portainer:
    image: portainer/portainer:1.24.1-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/portainer_password:/tmp/portainer_password
    ports:
      - 9000:9000
    command: -H unix:///var/run/docker.sock --no-auth

  postgres:
    image: postgres:12.3-alpine
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: always
    volumes:
      - /var/nextcloud/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:6.0.4-alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: always
    # command: bash -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"

  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - /var/nextcloud/www/html:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud

  nextcloud:
    image: nextcloud:19.0.0-fpm-alpine
    container_name: nextcloud-app
    hostname: nextcloud-app
    restart: always
    volumes:
      - /var/nextcloud/data:/var/nextcloud/data
      - /var/nextcloud/www/html:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_DATA_DIR=/var/nextcloud/data
      - REDIS_HOST=nextcloud-redis
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
      - redis

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.8.1
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      TZ: "America/Los Angeles"
      WEBPASSWORD: admin
    # Volumes store your data between container upgrades
    volumes:
       - ./pihole/etc/pihole:/etc/pihole
       - ./pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
