version: '3.2'

services:
  postgres:
    image: postgres:12.3-alpine
    container_name: nextcloud-db
    hostname: nextcloud-db
    restart: always
    volumes:
      - /var/nextcloud/postgresql/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - nextcloud_network

  redis:
    image: redis:6.0.4-alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    restart: always
    # command: bash -c "echo never > /sys/kernel/mm/transparent_hugepage/enabled"
    networks:
      - nextcloud_network

  nginx:
    image: nginx:1.19.0-alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - /var/nextcloud/www/html:/var/www/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nextcloud
    networks:
      - nextcloud_network

  nextcloud:
    image: nextcloud:19.0.0-fpm-alpine
    container_name: nextcloud-app
    hostname: nextcloud-app
    restart: always
    volumes:
      - /var/nextcloud/data:/var/nextcloud/data
      - /var/nextcloud/www/html:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - NEXTCLOUD_DATA_DIR=/var/nextcloud/data
      - REDIS_HOST=nextcloud-redis
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - postgres
      - redis
    networks:
      - nextcloud_network

  pihole:
    container_name: pihole
    image: pihole/pihole:v5.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'America/Los Angeles'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
       - /var/pihole/etc/pihole:/etc/pihole
       - /var/pihole/etc/dnsmasq.d:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 1.1.1.1
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  nextcloud_network:
